https://www.perplexity.ai/search/045ecda7-23bf-4d76-9155-fcb886e2425e

In [5]:
#在終端機上打 pip install -r requirements.txt

import numpy as np
np.random.random()
np.random.random(3)
np.random.random(size=3)
np.random.random((3, 4))
np.random.random(size=(3,4))

array([[0.30999859, 0.75294933, 0.80854509, 0.42407406],
       [0.04647289, 0.39190537, 0.71951122, 0.35225983],
       [0.48062038, 0.90549947, 0.61737787, 0.17386184]])

In [ ]:
from numpy.random import normal as nl

normal_value = nl(size=(3, 4))
#ndarray常用的實體屬性
type(normal_value)

#ndim維度數=2
normal_value.ndim

#size為數量=12
normal_value.size

#shape=(3,4)
normal_value.shape

#dtype='float64'
normal_value.dtype

dtype('float64')

In [9]:
#ndarray,陣列運算
normal_value * 10

array([[ -5.9282161 ,   7.49912431,   8.06325518, -14.37672675],
       [ -2.1789871 ,  -9.78941943,  -0.13806628, -10.18572295],
       [  7.68128724,  12.36956663,  -7.76248396,   3.90516995]])

In [ ]:
#ndarray,的統計
normal_value.sum()

#axis=0為行
normal_valuesum0=normal_value.sum(axis=0)
print(normal_valuesum0)
#axis=1為列
normal_valuesum1=normal_value.sum(axis=1)
print(normal_valuesum1)

[-0.0425916   1.00792715  0.01627049 -2.06572798]
[-0.47425634 -2.22921958  1.61935399]
